LKE-2456 export graph as an image
Linkurious/lke-plugin-image-export pull request #1
Opened 2020-12-28 10:14 UTC by aminerhanemi

2020-12-29 09:41 UTC, francescoinfante requested changes

2020-12-29 09:41 UTC, francescoinfante commented on .gitignore
> +custom-image-export.lke/buildcache
it's bad practice to push the whole built artifact in the codebase. wheneve you change something, you also have to change the artifact making PR unreadable.
Instead, customers should be able to build very easily with npm run build for example.

(also we are going to ship *.lke packages as releases)

2020-12-29 09:41 UTC, francescoinfante commented on package.json
> +  "dependencies": {
how do we put ogma in here?

2020-12-29 09:41 UTC, francescoinfante commented on src/backend/routeHandler.ts
> +  options.router.get('/getVisualizationConfiguration/:id&:sourceKey', async (req, res) => {
this is a very non standard way to get parameters, instead, let's pass them as querystring.

2020-12-29 09:41 UTC, francescoinfante commented on custom-image-export.lke/public/index.html
> +<html class="no-js" lang="">
We should create a separate folder for the assets instead of the *.lke itself directly

2020-12-29 13:38 UTC, aminerhanemi commented on package.json
> +  "dependencies": {
ogma is part of ogma-helper

2020-12-30 15:21 UTC, francescoinfante submitted a review, later dismissed

2020-12-30 16:21 UTC, merged